name: Test Django
on:
   workflow_dispatch:
   push:
     branches: [main]
   
jobs:
   django_test:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: Setup Python 3.10
           uses: actions/setup-python@v2
           with:
               python-version: "3.10"
         - name: upgrade pip 
           run: pip install --upgrade pip      
         - name: Install requirements
           run: pip install -r growii_django/requirements.txt
         - name: Run Django Tests
           run: python growii_django/manage.py test

